### ISSUE TITLE
Allow partitioning by user-defined key

### ISSUE THREAD

**Issue by piotrlg9** [gravity9-tech/mongocdc#17]
There may be cases when default random distribution (by _id) may not be the best option.

For example:
* collection A contains events which are referencing other collection (B) and we want to observe events in A in order specified by "_id" from B

collection A:

```json
[{
  "_id": 1,
  "event": [ "details..." ],
  "collectionB_Id": 100
},
{
  "_id": 2,
  "event": [ "details..." ],
  "collectionB_Id": 100
},
{
  "_id": 3,
  "event": [ "details..." ],
  "collectionB_Id": 100
}]
```

All events for these documents should be handled inside the same partition.

In such cases it would be useful to define own partitioning key.

**Comment by PiotrGravity** [comment]
Solved in #40
