### ISSUE TITLE
Allow more configuration options

### ISSUE THREAD

**Issue by BartekGravity** [gravity9-tech/mongocdc#2]
Allow users to customize the behaviour of the library. Things to consider:

1. Change config collection names
2. Change which field to use for keying
3. Allow change stream customization (check how Change Streams themselves can be customized and allow users to take advantage of it)

**Comment by meehaws** [comment]
Please consider:
* Max Await time for change streams
* documents returned by change stream (fullDocument, fullDocumentBeforeChange, etc)
