### ISSUE TITLE
Correct thread and Runnable usage

### ISSUE THREAD

**Issue by piotrlg9** [gravity9-tech/mongocdc#31]
`Thread` class is used internally by MongoChangeStreamWorker which is also Runnable.
This is not according to standards and probably should be corrected.

There are two possible solutions:
* MongoChangeStreamWorker implements Runnable - recommended (without Thread inside, thread created in MongoCDCManager)
* MongoChangeStreamWorker extends Thread - possible, but less preferable

MongoChangeStreamWorker can still refer to thread (if required at all) - via Thread.currentThread.

**Comment by PiotrGravity** [comment]
Resolved with #39
