### ISSUE TITLE
Add unique identification of instances in logs

### ISSUE THREAD

**Issue by piotrlg9** [gravity9-tech/mongocdc#32]
While logging in MongoCDCManager or MongoChangeStreamWorker, unique instance ID should be added in logs so user can verify for which collection, partition or database error occured.

Things to do:
* generate unique instance ID for each instance of MongoCDCManager & MongoChangeStreamWorker (like "cdcm_sales_individuals_001")
* log this instance ID during start along with unique instance paramenters:
  * for manager: (optional) masked URI, required: database name, collection name
  * for worker: manager id, partition id
* correct existing logging so every message contains unique instance id

**Comment by PiotrGravity** [comment]
Solved in #43
