### ISSUE TITLE
Disable MongoChangeStreamWorker logs or change to DEBUG mode

### ISSUE THREAD

**Issue by piotr-bugara-gravity9** [gravity9-tech/mongocdc#7]
Currently, the MongoCDC library prints a massive ammount of logs from MongoChangeStreamWorker:

`11:22:49.089 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411F8000000032B0229296E04
11:22:49.553 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411F9000000012B0229296E04
11:22:49.553 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411F9000000012B0229296E04
11:22:50.111 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411F9000000032B0229296E04
11:22:50.562 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FA000000012B0229296E04
11:22:50.562 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FA000000012B0229296E04
11:22:51.128 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FA000000032B0229296E04
11:22:51.580 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FB000000012B0229296E04
11:22:51.580 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FB000000012B0229296E04
11:22:52.146 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FB000000032B0229296E04
11:22:52.601 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FC000000012B0229296E04
11:22:52.601 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FC000000012B0229296E04
11:22:53.165 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FC000000032B0229296E04
11:22:53.618 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FD000000012B0229296E04
11:22:53.618 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FD000000012B0229296E04
11:22:54.182 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FD000000032B0229296E04
11:22:54.631 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FE000000012B0229296E04
11:22:54.631 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FE000000012B0229296E04
11:22:55.200 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FE000000032B0229296E04
11:22:55.650 [Thread-0] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 0, resumeToken: 82658411FF000000012B0229296E04
11:22:55.650 [Thread-2] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 2, resumeToken: 82658411FF000000012B0229296E04
11:22:56.209 [Thread-1] INFO  com.gravity9.mongocdc.MongoChangeStreamWorker - Updating resume token for partition 1, resumeToken: 82658411FF000000032B0229296E04`

They should be disabled, or the log level should be changed to DEBUG.

**Comment by PiotrGravity** [comment]
I think TRACE will the most suitable here

**Comment by PiotrGravity** [comment]
Resolved in #41
